# --- Black Configuration ---
[tool.black]
line-length = 88
target-version = ['py313']

# --- isort Configuration ---
[tool.isort]
profile = "black" # Make isort compatible with Black
line_length = 88
multi_line_output = 3 # Vertical Hanging Indent, often preferred with Black
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
